-- AlterTable
ALTER TABLE "Certification" ALTER COLUMN "issueDate" SET DATA TYPE TEXT,
ALTER COLUMN "expiryDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Education" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Experience" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
